# Generated by Django 6.0.3 on 2026-04-07 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("date_start", models.DateField(blank=True, null=True)),
                ("date_completed", models.DateField(blank=True, null=True)),
                ("link", models.CharField(blank=True, max_length=2000, null=True)),
                ("background_color", models.CharField(max_length=20)),
                ("text_color", models.CharField(max_length=20)),
                ("icon", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("ects", models.IntegerField()),
                ("background_color", models.CharField(max_length=20)),
                ("text_color", models.CharField(max_length=20)),
                ("icon", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("link", models.CharField(max_length=2000)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="media/photos/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Type_Framework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("background_color", models.CharField(max_length=20)),
                ("text_color", models.CharField(max_length=20)),
                ("icon", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Type_Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("interest_level", models.IntegerField(default=3)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/technologies/"
                    ),
                ),
                ("link", models.CharField(max_length=2000)),
                ("background_color", models.CharField(max_length=20)),
                ("text_color", models.CharField(max_length=20)),
                ("icon", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Discipline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("ects", models.IntegerField()),
                ("background_color", models.CharField(max_length=20)),
                ("text_color", models.CharField(max_length=20)),
                ("icon", models.CharField(max_length=100)),
                (
                    "Course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="portfolio.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("date_completed", models.DateField(blank=True, null=True)),
                ("link", models.CharField(blank=True, max_length=2000, null=True)),
                ("background_color", models.CharField(max_length=20)),
                ("text_color", models.CharField(max_length=20)),
                ("icon", models.CharField(max_length=100)),
                (
                    "Discipline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="portfolio.discipline",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Discipline_Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Discipline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discipline_teachers",
                        to="portfolio.discipline",
                    ),
                ),
                (
                    "Teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discipline_teachers",
                        to="portfolio.teacher",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Type_Frameworks_Competency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("guidance", models.TextField()),
                ("background_color", models.CharField(max_length=20)),
                ("text_color", models.CharField(max_length=20)),
                ("icon", models.CharField(max_length=100)),
                (
                    "Type_Framework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competencies",
                        to="portfolio.type_framework",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Type_Frameworks_Competencies_Levels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("background_color", models.CharField(max_length=20)),
                ("text_color", models.CharField(max_length=20)),
                ("icon", models.CharField(max_length=100)),
                (
                    "Type_Frameworks_Competency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="type_frameworks_competency",
                        to="portfolio.type_frameworks_competency",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Certification_Competency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Certification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certification_competencies",
                        to="portfolio.certification",
                    ),
                ),
                (
                    "Level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="certification_competencies",
                        to="portfolio.type_frameworks_competencies_levels",
                    ),
                ),
                (
                    "Competency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="certification_competencies",
                        to="portfolio.type_frameworks_competency",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Type_Frameworks_Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("value", models.IntegerField()),
                ("background_color", models.CharField(max_length=20)),
                ("text_color", models.CharField(max_length=20)),
                ("icon", models.CharField(max_length=100)),
                ("sort", models.IntegerField()),
                (
                    "Type_Framework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levels",
                        to="portfolio.type_framework",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="type_frameworks_competencies_levels",
            name="Type_Frameworks_Level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="type_frameworks_level",
                to="portfolio.type_frameworks_level",
            ),
        ),
        migrations.CreateModel(
            name="Project_Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_technologies",
                        to="portfolio.project",
                    ),
                ),
                (
                    "Technology",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_technologies",
                        to="portfolio.type_technology",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Discipline_Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Discipline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discipline_technologies",
                        to="portfolio.discipline",
                    ),
                ),
                (
                    "Technology",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discipline_technologies",
                        to="portfolio.type_technology",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Certification_Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Certification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certification_technologies",
                        to="portfolio.certification",
                    ),
                ),
                (
                    "Technology",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certification_technologies",
                        to="portfolio.type_technology",
                    ),
                ),
            ],
        ),
    ]
