# Generated by Django 6.0.3 on 2026-04-06 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("ects", models.IntegerField()),
                ("background_color", models.CharField(max_length=20)),
                ("text_color", models.CharField(max_length=20)),
                ("icon", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Type_Framework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("background_color", models.CharField(max_length=20)),
                ("text_color", models.CharField(max_length=20)),
                ("icon", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Discipline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("ects", models.IntegerField()),
                ("background_color", models.CharField(max_length=20)),
                ("text_color", models.CharField(max_length=20)),
                ("icon", models.CharField(max_length=100)),
                (
                    "Course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="portfolio.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Type_Frameworks_Competency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("guidance", models.TextField()),
                ("background_color", models.CharField(max_length=20)),
                ("text_color", models.CharField(max_length=20)),
                ("icon", models.CharField(max_length=100)),
                (
                    "Type_Framework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competencies",
                        to="portfolio.type_framework",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Type_Frameworks_Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("value", models.IntegerField()),
                ("background_color", models.CharField(max_length=20)),
                ("text_color", models.CharField(max_length=20)),
                ("icon", models.CharField(max_length=100)),
                ("sort", models.IntegerField()),
                (
                    "Type_Framework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="levels",
                        to="portfolio.type_framework",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Type_Frameworks_Competencies_Levels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("background_color", models.CharField(max_length=20)),
                ("text_color", models.CharField(max_length=20)),
                ("icon", models.CharField(max_length=100)),
                (
                    "Type_Frameworks_Competency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="type_frameworks_competency",
                        to="portfolio.type_frameworks_competency",
                    ),
                ),
                (
                    "Type_Frameworks_Level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="type_frameworks_level",
                        to="portfolio.type_frameworks_level",
                    ),
                ),
            ],
        ),
    ]
