# Generated by Django 6.0.3 on 2026-05-11 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("date_start", models.DateField(blank=True, null=True)),
                ("date_completed", models.DateField(blank=True, null=True)),
                ("link", models.CharField(blank=True, max_length=2000, null=True)),
                ("background_color", models.CharField(max_length=20)),
                ("text_color", models.CharField(max_length=20)),
                ("icon", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("ects", models.IntegerField()),
                ("background_color", models.CharField(max_length=20)),
                ("text_color", models.CharField(max_length=20)),
                ("icon", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("link", models.CharField(max_length=2000)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="media/photos/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Type_Framework",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("background_color", models.CharField(max_length=20)),
                ("text_color", models.CharField(max_length=20)),
                ("icon", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Type_Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("interest_level", models.IntegerField(default=3)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="media/technologies/"
                    ),
                ),
                ("link", models.CharField(max_length=2000)),
                ("background_color", models.CharField(max_length=20)),
                ("text_color", models.CharField(max_length=20)),
                ("icon", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Discipline",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("ects", models.IntegerField()),
                (
                    "finalgrade",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("background_color", models.CharField(max_length=20)),
                ("text_color", models.CharField(max_length=20)),
                ("icon", models.CharField(max_length=100)),
                (
                    "Course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disciplines",
                        to="portfolio.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FinalProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("summary", models.TextField()),
                ("year", models.IntegerField()),
                ("students", models.CharField(max_length=500)),
                ("email", models.CharField(max_length=200)),
                ("supervisor", models.CharField(max_length=200)),
                (
                    "report_link",
                    models.CharField(blank=True, max_length=2000, null=True),
                ),
                ("keywords", models.CharField(blank=True, max_length=500, null=True)),
                ("areas", models.CharField(blank=True, max_length=500, null=True)),
                ("image", models.CharField(blank=True, max_length=2000, null=True)),
                ("rating", models.IntegerField(blank=True, null=True)),
                ("background_color", models.CharField(default="", max_length=20)),
                ("text_color", models.CharField(default="", max_length=20)),
                ("icon", models.CharField(default="", max_length=100)),
                (
                    "Course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="final_projects",
                        to="portfolio.course",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("date_completed", models.DateField(blank=True, null=True)),
                ("link", models.CharField(blank=True, max_length=2000, null=True)),
                ("background_color", models.CharField(max_length=20)),
                ("text_color", models.CharField(max_length=20)),
                ("icon", models.CharField(max_length=100)),
                (
                    "Discipline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="portfolio.discipline",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Discipline_Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Discipline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discipline_teachers",
                        to="portfolio.discipline",
                    ),
                ),
                (
                    "Teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discipline_teachers",
                        to="portfolio.teacher",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Type_Frameworks_Competency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("guidance", models.TextField()),
                ("background_color", models.CharField(max_length=20)),
                ("text_color", models.CharField(max_length=20)),
                ("icon", models.CharField(max_length=100)),
                (
                    "Type_Framework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Type_Frameworks_Competencies",
                        to="portfolio.type_framework",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Type_Frameworks_Competencies_Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("background_color", models.CharField(max_length=20)),
                ("text_color", models.CharField(max_length=20)),
                ("icon", models.CharField(max_length=100)),
                (
                    "Type_Frameworks_Competency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="type_frameworks_competencies_levels",
                        to="portfolio.type_frameworks_competency",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Certification_Competency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Certification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certification_competencies",
                        to="portfolio.certification",
                    ),
                ),
                (
                    "Level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="certification_competencies",
                        to="portfolio.type_frameworks_competencies_level",
                    ),
                ),
                (
                    "Competency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="certification_competencies",
                        to="portfolio.type_frameworks_competency",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Type_Frameworks_Level",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("value", models.IntegerField()),
                ("background_color", models.CharField(max_length=20)),
                ("text_color", models.CharField(max_length=20)),
                ("icon", models.CharField(max_length=100)),
                ("sort", models.IntegerField()),
                (
                    "Type_Framework",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Type_Frameworks_Levels",
                        to="portfolio.type_framework",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="type_frameworks_competencies_level",
            name="Type_Frameworks_Level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="type_frameworks_competencies_levels",
                to="portfolio.type_frameworks_level",
            ),
        ),
        migrations.CreateModel(
            name="Project_Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_technologies",
                        to="portfolio.project",
                    ),
                ),
                (
                    "Technology",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_technologies",
                        to="portfolio.type_technology",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Discipline_Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Discipline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discipline_technologies",
                        to="portfolio.discipline",
                    ),
                ),
                (
                    "Technology",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discipline_technologies",
                        to="portfolio.type_technology",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Certification_Technology",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Certification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certification_technologies",
                        to="portfolio.certification",
                    ),
                ),
                (
                    "Technology",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certification_technologies",
                        to="portfolio.type_technology",
                    ),
                ),
            ],
        ),
    ]
