# Generated by Django 6.0.3 on 2026-05-11 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Type_Frameworks_Competencies_Level",
            new_name="Type_Frameworks_Competencies_Levels",
        ),
    ]
