# Generated by Django 6.0.3 on 2026-04-07 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_teacher"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discipline_Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Discipline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discipline_teachers",
                        to="portfolio.discipline",
                    ),
                ),
                (
                    "Teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discipline_teachers",
                        to="portfolio.teacher",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("date_completed", models.DateField(blank=True, null=True)),
                ("link", models.CharField(blank=True, max_length=2000, null=True)),
                ("background_color", models.CharField(max_length=20)),
                ("text_color", models.CharField(max_length=20)),
                ("icon", models.CharField(max_length=100)),
                (
                    "Discipline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects",
                        to="portfolio.discipline",
                    ),
                ),
            ],
        ),
    ]
