# Generated by Django 6.0.5 on 2026-05-13 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio",
            "0002_rename_type_frameworks_competencies_level_type_frameworks_competencies_levels",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=200)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, default="")),
                ("ects", models.IntegerField()),
                (
                    "finalgrade",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("text_color", models.CharField(max_length=20)),
                ("icon", models.CharField(max_length=100)),
            ],
        ),
    ]
