# Generated by Django 6.0.5 on 2026-05-13 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_job"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Job",
        ),
    ]
